services:
  - type: web
    name: tomato-leaf-api
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: CHRISKEY
        sync: false  # Never put real keys here. Add via Render's UI.